"use client";
import { FormEvent, useState } from "react";
import { Mail, MapPin, MessageCircle } from "lucide-react";
const field = "mt-2 h-12 w-full rounded-xl border border-[#292421]/15 bg-white px-4 text-sm outline-none focus:border-[#292421] focus:ring-2 focus:ring-[#a56a4b]/50";
export default function ContactPage() {
  const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setStatus(""); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) setError(body.error); else { setStatus(body.message); form.reset(); } } catch { setError("Could not reach the server."); } finally { setLoading(false); } }
  return <section className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20"><div className="grid overflow-hidden rounded-[32px] border border-[#292421]/10 bg-[#f3efeb] shadow-xl lg:grid-cols-[0.8fr_1.2fr]"><div className="bg-[#292421] p-8 text-white sm:p-12"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#a56a4b]">Contact</p><h1 className="mt-3 font-manrope text-6xl font-bold leading-[0.88] tracking-[-0.06em]">Let’s talk <em className="font-playfair text-[#a56a4b]">style.</em></h1><p className="mt-6 text-sm leading-7 text-[#999]">Questions about an order, fit, collaboration or career? Send it here—your message is saved securely for our team.</p><div className="mt-10 space-y-5 text-sm"><p className="flex gap-3"><Mail className="h-5 w-5 text-[#a56a4b]"/> support@threadntrends.pk</p><p className="flex gap-3"><MessageCircle className="h-5 w-5 text-[#a56a4b]"/> Mon–Sat · 10am–6pm PKT</p><p className="flex gap-3"><MapPin className="h-5 w-5 text-[#a56a4b]"/> Pakistan · Online store</p></div></div><div className="p-7 sm:p-12"><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold">Name<input name="name" className={field} minLength={2} maxLength={100} required /></label><label className="text-xs font-bold">Email<input name="email" type="email" className={field} required /></label><label className="text-xs font-bold sm:col-span-2">Subject<select name="subject" className={field} defaultValue="Order help"><option>Order help</option><option>Size & product</option><option>Exchange or return</option><option>Careers</option><option>Collaboration</option><option>General enquiry</option></select></label><label className="text-xs font-bold sm:col-span-2">Message<textarea name="message" minLength={10} maxLength={5000} required className="mt-2 min-h-36 w-full resize-none rounded-xl border border-[#292421]/15 bg-white p-4 text-sm outline-none focus:border-[#292421] focus:ring-2 focus:ring-[#a56a4b]/50" /></label><button disabled={loading} className="rounded-full bg-[#a56a4b] px-6 py-4 text-[11px] font-extrabold uppercase tracking-[0.08em] sm:col-span-2">{loading ? "Sending…" : "Send message"}</button></form>{status && <p className="mt-5 rounded-xl bg-[#a56a4b]/25 p-4 text-sm font-medium">{status}</p>}{error && <p className="mt-5 rounded-xl bg-[#7f5539]/10 p-4 text-sm text-[#a52d21]">{error}</p>}</div></div></section>;
}
