"use client";
import { FormEvent, useState } from "react";
import { PackageSearch } from "lucide-react";
type Order = { reference: string; status: string; total: number; createdAt: string; city: string };
const input = "mt-2 h-12 w-full rounded-xl border border-[#292421]/15 bg-white px-4 text-sm outline-none focus:border-[#292421] focus:ring-2 focus:ring-[#a56a4b]/50";
export default function TrackPage() {
  const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setOrder(null); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/orders/track", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reference: form.get("reference"), email: form.get("email") }) }); const data = await response.json(); if (!response.ok) setError(data.error); else setOrder(data.order); } catch { setError("Could not reach the server."); } finally { setLoading(false); } }
  return <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6"><div className="grid overflow-hidden rounded-[32px] border border-[#292421]/10 bg-[#f3efeb] shadow-xl md:grid-cols-2"><div className="bg-[#292421] p-8 text-white sm:p-12"><PackageSearch className="h-12 w-12 text-[#a56a4b]"/><p className="mt-12 text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#756c65]">Order status</p><h1 className="mt-2 font-manrope text-6xl font-bold leading-[0.9] tracking-[-0.06em]">Track your <em className="font-playfair text-[#a56a4b]">order.</em></h1><p className="mt-5 text-sm leading-7 text-[#999]">Use the reference shown after checkout and the same email used for your order.</p></div><div className="p-8 sm:p-12"><form onSubmit={submit} className="space-y-5"><label className="block text-xs font-bold">Order reference<input name="reference" className={input} placeholder="TNT-2026-ABC123" required /></label><label className="block text-xs font-bold">Checkout email<input name="email" type="email" className={input} placeholder="you@example.com" required /></label><button disabled={loading} className="w-full rounded-full bg-[#a56a4b] py-4 text-[11px] font-extrabold uppercase tracking-[0.08em] disabled:opacity-50">{loading ? "Looking…" : "Track order"}</button></form>{error && <p className="mt-5 rounded-xl bg-[#7f5539]/10 p-4 text-sm text-[#a52d21]">{error}</p>}{order && <div className="mt-6 rounded-[22px] bg-white p-6"><span className="rounded-full bg-[#a56a4b] px-3 py-1 text-[10px] font-extrabold uppercase">{order.status}</span><h2 className="mt-4 font-manrope text-2xl font-bold">{order.reference}</h2><p className="mt-2 text-sm text-[#68665f]">Placed {new Date(order.createdAt).toLocaleDateString()} · Delivery city: {order.city}</p><p className="mt-4 font-bold">PKR {order.total.toLocaleString()}</p></div>}</div></div></section>;
}
