"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
export default function Footer() {
  const [message, setMessage] = useState(""); const [joining, setJoining] = useState(false);
  async function join(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setJoining(true); const form = event.currentTarget; const email = String(new FormData(form).get("email") ?? ""); try { const response = await fetch("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json(); setMessage(response.ok ? data.message : data.error); if (response.ok) form.reset(); } catch { setMessage("Could not join right now."); } finally { setJoining(false); } }
  const instagram = process.env.NEXT_PUBLIC_INSTAGRAM_URL || "https://www.instagram.com/"; const facebook = process.env.NEXT_PUBLIC_FACEBOOK_URL || "https://www.facebook.com/";
  const links = [["FAQ","/faq"],["Track order","/track"],["Contact us","/contact"],["Size guide","/size-guide"],["Exchange & returns","/returns"],["Shipping","/shipping"]];
  return <footer className="bg-[#111] pb-6 pt-[70px] text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 md:grid-cols-[1.6fr_1fr_1fr_1fr] md:gap-14"><div><div className="font-manrope text-[clamp(35px,5vw,70px)] font-extrabold leading-[0.85] tracking-[-0.06em]">Thread n <em className="font-playfair not-italic text-[#b6ff39]">Trends.</em></div><p className="mt-3 max-w-[430px] leading-relaxed text-[#888]">Contemporary clothing and accessories for people who refuse to dress like everyone else.</p><form onSubmit={join} className="mt-6 flex max-w-[440px] border-b border-[#555]"><input name="email" type="email" required placeholder="Email for new drops" aria-label="Email for new drops" className="flex-1 border-0 bg-transparent py-3 text-white outline-none"/><button disabled={joining} className="bg-transparent text-white disabled:opacity-50">{joining ? "Joining…" : "Join ↗"}</button></form>{message && <p className="mt-2 text-xs text-[#b6ff39]">{message}</p>}</div><div><h4 className="mb-4 text-[10px] uppercase tracking-[0.16em] text-[#666]">Shop</h4><Link href="/products" className="block py-1.5 text-sm text-[#bbb] hover:text-white">New arrivals</Link><Link href="/products?category=men" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Men</Link><Link href="/products?category=women" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Women</Link><Link href="/lookbook" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Lookbook</Link></div><div><h4 className="mb-4 text-[10px] uppercase tracking-[0.16em] text-[#666]">Help</h4>{links.map(([label,href])=><Link key={href} href={href} className="block py-1.5 text-sm text-[#bbb] hover:text-white">{label}</Link>)}</div><div><h4 className="mb-4 text-[10px] uppercase tracking-[0.16em] text-[#666]">Brand</h4><Link href="/about" className="block py-1.5 text-sm text-[#bbb] hover:text-white">About</Link><a href={instagram} target="_blank" rel="noreferrer" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Instagram ↗</a><a href={facebook} target="_blank" rel="noreferrer" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Facebook ↗</a><Link href="/careers" className="block py-1.5 text-sm text-[#bbb] hover:text-white">Careers</Link></div></div><div className="mt-16 flex flex-wrap justify-between gap-3 border-t border-[#2b2b2b] pt-5 text-[10px] text-[#666]"><span>© 2026 Thread n Trends</span><span><Link href="/privacy" className="hover:text-white">Privacy</Link> · <Link href="/terms" className="hover:text-white">Terms</Link></span></div></div></footer>;
}
